services:
  accounts:
    image: akuchera/accounts:2
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - microservice-bank
  cards:
    image: akuchera/cards:2
    container_name: cards-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - microservice-bank
  loans:
    image: akuchera/loans:2
    container_name: loans-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - microservice-bank
  configserver:
    image: akuchera/configserver:2
    container_name: configserver
    ports:
      - "8071:8071"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - microservice-bank
networks:
  microservice-bank:
    driver: bridge
