global:
    configMapName: microbankdev-configmap
    activeProfile: default
    configServerURL: configserver:http://configserver:8071/
    eurekaServerURL: http://eurekaserver:8070/eureka/
    keyCloakURL: http://keycloak.default.svc.cluster.local:80/realms/dev/protocol/openid-connect/certs
    openTelemetryJavaAgent: -javaagent:/app/libs/opentelemetry-javaagent-1.33.5.jar
    otelExporterEndPoint: http://tempo-grafana-tempo-distributor:4317
    otelMetricsExporter: none
    rabbitMqHost: rabbitmq.default.svc.cluster.local
    rabbitMqPort: 5672
    rabbitMqUsername: guest
    rabbitMqPassword: guest
    rabbitMqConnectionTimeout: 10s
